# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

THRESHOLD = (10**-6).to_f
class Fixnum
  def t
    self*(self+1)/2
  end

  def is_t?
    result = (Math.sqrt(1 + 8*self) - 1)*0.5
    (result - result.to_i) < THRESHOLD
  end

  def p
    self*(3*self - 1) / 2
  end

  def is_p?
    result = (1 + Math.sqrt(1 + 24*self))/6
    (result - result.to_i) < THRESHOLD
  end

  def h
    self*(2*self - 1)
  end

  def is_h?
    result = (1 + Math.sqrt(1 + 8*self))/4
    (result - result.to_i) < THRESHOLD
  end
end

i = 286
loop do
  tn = i.t
  if tn.is_p? and tn.is_h?
    puts tn
    break
  end
  i += 1
end




